theme: minima
title: My first Github page
author: Tobias

![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

```
String age = 12;

if (age = 12){
System.out.println("age ist gleich 12");
}
```
